# Generated by Django 4.0.1 on 2022-02-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
