# Generated by Django 4.0.1 on 2022-02-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexique', '0002_photo_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='caption',
            new_name='romanji',
        ),
        migrations.AddField(
            model_name='photo',
            name='traduction',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
