# Generated by Django 4.0.1 on 2022-01-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_ideotype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideogramm',
            old_name='Name',
            new_name='Romanji',
        ),
        migrations.AddField(
            model_name='ideogramm',
            name='id_type_ideo',
            field=models.IntegerField(default=1),
        ),
    ]
