# Generated by Django 4.0.1 on 2022-02-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_ideogramm_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideogramm',
            name='Name',
        ),
    ]
