# Generated by Django 4.0.1 on 2022-02-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_remove_ideogramm_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ideogramm',
        ),
    ]
