# Generated by Django 4.0.1 on 2022-02-01 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_alter_ideogramm_img_link_alter_ideogramm_romanji_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideogramm',
            old_name='Romanji',
            new_name='romanji',
        ),
    ]
