# Generated by Django 4.0.1 on 2022-02-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_rename_romanji_ideogramm_romaji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideogramm',
            old_name='romaji',
            new_name='romanji',
        ),
    ]
