# Generated by Django 4.0.1 on 2022-02-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_delete_ideogramm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ideogramm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('romanji', models.CharField(max_length=50)),
                ('Img_link', models.CharField(max_length=100)),
                ('id_type_ideo', models.IntegerField(default=1)),
            ],
        ),
    ]
