# Generated by Django 4.0.1 on 2022-02-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_ideogramm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideogramm',
            name='Img_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ideogramm',
            name='id_type_ideo',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='ideogramm',
            name='romanji',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
