# Generated by Django 4.0.1 on 2022-02-02 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_remove_ideogramm_id_type_ideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideogramm',
            name='ideotype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.ideotype'),
        ),
    ]
